#!/bin/bash

source "$(dirname $0)/../dokku_common"

DB_ROOT="$DOKKU_ROOT/.memcached"
DB_IMAGE="${MEMCACHE_IMAGE:-memcached}"
DB_CONTAINER_LINK="memcached"
DB_CONTAINER_VOLUME="${MEMCACHE_CONTAINER_VOLUME:-/var/lib/memcached}"
DB_PORT="${MEMCACHE_PORT:-11211}"

function memcached_for_app() {
  verify_app_name "$1"
  DB_VOLUME="$DB_ROOT/$APP"
  DB_CONTAINER="memcached_app_$APP"
  DB_DATA_CONTAINER="memcached_data_$APP"
  DB_HOST="$DB_CONTAINER_LINK"
  DB_URL="memcached://$DB_CONTAINER_LINK:$DB_PORT"
}

function start_database_container() {
  docker run --name="$DB_DATA_CONTAINER" \
             -v "$DB_CONTAINER_VOLUME" \
             busybox:latest true 1>/dev/null 2>/dev/null || true

	docker run --detach \
             --name="$DB_CONTAINER" \
             --volumes-from="$DB_DATA_CONTAINER" \
             "$DB_IMAGE" >/dev/null
}

function ensure_database_container_is_running() {
  remove_container "$DB_CONTAINER"
  start_database_container 2>/dev/null || true
}
